### PR TITLE
Prepare for P3 modularization

### PR DESCRIPTION
**Pull request by manolo**
Connects to #68 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[version.html, line 16 at r1](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69#-LEsgfAI8deqqxNB8jos:-LEsgfAI8deqqxNB8jot:b39pefa) ([raw file](https://github.com/vaadin/vaadin-material-styles/blob/213d7d0554f701dbfe31cb9c0bd58559036e8728/version.html#L16)):*
> ```HTML
>     customElements.define('vaadin-material-styles', Lumo);
> 
>     window.Vaadin.Lumo = Lumo;
> ```

Lumo -> Material

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

---

*[version.html, line 16 at r1](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69#-LEsgfAI8deqqxNB8jos:-LEsgswr2_mXGiz4vCs7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-material-styles/blob/213d7d0554f701dbfe31cb9c0bd58559036e8728/version.html#L16)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Lumo -> Material
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @tomivirkki and @manolo)

---

*[version.html, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69#-LEst07tA6zs0w8-Mb5e:-LEsu1tT6RjrqRjvlN3P:bsye8j2) ([raw file](https://github.com/vaadin/vaadin-material-styles/blob/4307e9fd47586bfacfa68417462def0b79b96de1/version.html#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

😒 Lumo
</blockquote></details>

That happens when not using regex, I thought was faster manually  😩 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @tomivirkki)

---

*[version.html, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69#-LEst07tA6zs0w8-Mb5e:-LEsudDTCqpFycOCotyq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-material-styles/blob/4307e9fd47586bfacfa68417462def0b79b96de1/version.html#L14)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

That happens when not using regex, I thought was faster manually  😩 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/69#-:-LEsvNgY64GRujv_xp4y:bnfp4nl)*

**Pull request merged**
