### PR TITLE
BREAKING: use font Roboto bundle instead of Google Fonts

### LINKED ISSUE #77: External dependency might cause slow page load/errors
It took me a while to catch this, but debugging a slow page load I've found the cause to be this line in `typography.html`:

```
<!-- Import Roboto from Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" crossorigin="anonymous">
```

If a Vaadin app is used without Internet access or behind a captive portal, an external dependency like this might slow down page load or even throw errors.

P.S. I'm not even using `vaadin-material-styles`, but somehow it comes along with other dependencies via Flow webjars.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #77 

I marked this as a **BREAKING** change because it might potentially affect various things, e.g. we need to verify how this works with bundlers, and whether it affects [Flow theme integration](https://github.com/vaadin/flow/blob/master/flow-theme-integrations/material) by the fact that we are adding static resources.

When running `polymer-build` fonts will likely have to be added to the `extraDependencies` list. 
I will evaluate this using the Polymer starter. Also will check how Webpack works.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-styles/78)

### CODE REVIEW

**Comment by jouni** [comment]
Are we sure we want to bundle the fonts? I’m not convinced it’s the best option. I would’ve gone with opt-in. But I assume because it’s currently already forced, we don’t want to introduce a visually breaking change?

If we want to bundle the fonts, then let’s at least make sure to use the fonts the OS (like Android) already has, or the ones a user might have installed themselves. For example:

```css
@font-face {
         font-family: 'Roboto';
         src: local("Roboto Thin"), 
              url('fonts/roboto/Roboto-Thin.woff2') format('woff2'), 
              url('fonts/roboto/Roboto-Thin.woff') format('woff');
         font-weight: 100;
         font-style: normal;
       }
```

More information: https://stackoverflow.com/questions/3837249/font-face-src-local-how-to-use-the-local-font-if-the-user-already-has-it

Also, we need to make sure it’s possible to opt-out of using the Roboto font, even with the Material theme. AFAIK browsers should not load any web fonts unless there’s an element on the page that has a matching computed value for `font-family`. But, it would also be great to be able to opt-out from downloading the large style module in the first place (5.35 KB).

**Comment by web-padawan** [comment]
> I’m not convinced it’s the best option. I would’ve gone with opt-in. But I assume because it’s currently already forced, we don’t want to introduce a visually breaking change?

We can make it opt-in, sure. That sounds better to me as well, although it will most likely require us some work to update Flow integration, as I mentioned above.

For now, will remove the import from `typography.html`

**Comment by web-padawan** [comment]
@platosha I would like to hear your opinion regarding this change.

**Comment by web-padawan** [comment]
Actually, I feel like the CSS file would be better to use, so that we could recommend including it on the app level, or consider using various approaches to e.g. delay it etc. Trying to see how it works with the bundler now.

**Comment by web-padawan** [comment]
Confirmed to work with the Polymer CLI when placing stylesheet in the app shell:
https://github.com/vaadin/vaadin-core-elements-ux/tree/material-roboto

Note: link available to the Vaadiners only but generally related changes are these:

```json
  "extraDependencies": [
    "bower_components/vaadin-material-styles/fonts/**/*"
  ],
```

and HTML in the app shell:

```html
<link rel="stylesheet" href="../../bower_components/vaadin-material-styles/font-roboto.css">
```

**Comment by web-padawan** [comment]
@jouni could you take another look at this PR once you have time?

Once it is merged, we can release 2.0.0 so it could be potentially used at least with bower by overriding versions in `bower.json`. Major releases for the components might happen later though.

**Pull request merged**
